services:
  main_container:
    image: blender_colon:latest
    container_name: blender_colon_v0.0.1
    build:
      context: ..
      # cache_from:
      #   - blender_colon:latest
      dockerfile: .devcontainer/Dockerfile
      args:
        USER: ${USER}
    platform: linux/x86_64
    volumes:
      - ${PWD}/..:/home/${USER}/workspace
